apiVersion: v1
kind: ConfigMap
metadata:
  name: quilkin-config
data:
  quilkin.yaml: |
    version: v1alpha1
    proxy:
      port: 26001
    static:
      endpoints:
        - address: 127.0.0.1:8080
---
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: supertuxkart
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    spec:
      container: supertuxkart
      ports:
      - name: default
        containerPort: 26001
        container: quilkin
      health:
        initialDelaySeconds: 30
        periodSeconds: 60
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: /metrics
            prometheus.io/port: "9091"
        spec:
          containers:
          - name: supertuxkart
            image: gcr.io/agones-images/supertuxkart-example:0.2
          - name: quilkin
            image: us-docker.pkg.dev/quilkin/release/quilkin:0.1.0
            volumeMounts:
              - name: config
                mountPath: "/etc/quilkin"
            livenessProbe:
              httpGet:
                path: /live
                port: 9091
              initialDelaySeconds: 3
              periodSeconds: 2
          volumes:
            - name: config
              configMap:
                name: quilkin-config          
