apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: supertuxkart
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    spec:
      ports:
      - name: default
        containerPort: 8080
      health:
        initialDelaySeconds: 30
        periodSeconds: 60
      template:
        spec:
          containers:
          - name: supertuxkart
            image: gcr.io/agones-images/supertuxkart-example:0.2
